version: '3.8'

services:
  flask-app:
    build: .
    container_name: theputrasTools  # Explicitly name the container
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - PREFERRED_URL_SCHEME=https
    volumes:
      - .:/app  # Optional: This mounts your local app directory to the container's /app
      - /etc/localtime:/etc/localtime:ro  # Menyinkronkan waktu host dengan container
      - /etc/timezone:/etc/timezone:ro  # Menyinkronkan zona waktu
    restart: unless-stopped  # Optional: Ensures the container restarts unless stopped manually