version: '3.8'

services:
  flask-app:
    build: .
    container_name: theputrasTools  # Explicitly name the container
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - SICYCA_USER=23410100003
      - DB_HOST=172.16.3.3
      - DB_PORT=3306
      - DB_USERNAME=theputras
      - DB_PASSWORD=tpmroot1204
      - DB_DATABASE=theputras
      - SICYCA_PASS=368010
      - SECRET_KEY=fa1c6b4ef8dc9e7a9a8b1f81e924a1b33fdc2294a03b4cd6a4f4c6cfdb6a8f4e
      - PREFERRED_URL_SCHEME=https
    volumes:
      - .:/app  # Optional: This mounts your local app directory to the container's /app
      - /etc/localtime:/etc/localtime:ro  # Menyinkronkan waktu host dengan container
      - /etc/timezone:/etc/timezone:ro  # Menyinkronkan zona waktu
    restart: unless-stopped  # Optional: Ensures the container restarts unless stopped manually